#!/usr/bin/env python3
"""Render legal/*.md into standalone terms.html / privacy.html pages.

The repo has no build step and no markdown dependency, so rather than teach the
browser to parse markdown, the two legal documents are kept as markdown (the form
they were authored in, and the form that is easy to redline) and rendered to static
HTML once, here. **Re-run this after editing anything in legal/** — the .html files
are generated artifacts, don't hand-edit them:

    python build_legal.py

Only the markdown subset those two documents actually use is supported: ATX
headings, `- ` bullets, `**bold**`, `---` rules, and paragraphs. Anything fancier
would need a real parser; if a future edit needs it, add it here rather than
hand-patching the HTML.
"""
import html
import re

DOCS = [
    ("legal/terms.md", "terms.html", "Terms of Use", "privacy.html", "Privacy Policy"),
    ("legal/privacy.md", "privacy.html", "Privacy Policy", "terms.html", "Terms of Use"),
]

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — Wingman</title>
<link rel="icon" href="favicon.svg">
<script src="https://cdn.tailwindcss.com"></script>
<link rel="stylesheet" href="styles.css">
<!-- Generated by build_legal.py from {source} — do not edit by hand. -->
</head>
<body class="text-slate-900 bg-white">
<div class="max-w-3xl mx-auto px-5 py-10">
  <div class="flex items-center justify-between gap-4 mb-8 pb-6 border-b-2 border-slate-200">
    <a href="index.html" class="flex items-center gap-2 no-underline text-slate-900">
      <img src="favicon.svg" alt="" class="w-10 h-10 rounded-xl">
      <span class="font-heading font-extrabold text-xl">Wingman</span>
    </a>
    <a href="{sibling_href}" class="font-bold text-sm text-indigo-600 hover:underline">{sibling_label} &rarr;</a>
  </div>
  <article class="legal-doc">
{body}
  </article>
  <div class="mt-10 pt-6 border-t-2 border-slate-200">
    <a href="index.html" class="font-bold text-sm text-indigo-600 hover:underline">&larr; Back to Wingman</a>
  </div>
</div>
</body>
</html>
"""

# Stands in for a markdown two-space hard break between the line-splitting pass and
# the inline pass, which is where paragraph lines have already been joined.
HARD_BREAK = chr(0xE000)  # a private-use codepoint, so it cannot collide with document text

H_CLASSES = {
    1: 'font-heading font-extrabold text-3xl mb-2 mt-0',
    2: 'font-heading font-extrabold text-xl mt-8 mb-3',
    3: 'font-bold text-base mt-6 mb-2',
}


def inline(text):
    """Escape, then re-apply the inline markup we allow (bold, and two-space breaks)."""
    out = html.escape(text)
    out = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", out)
    # A markdown hard break (a line that ended in two spaces) arrives here as the
    # HARD_BREAK sentinel, because paragraph lines were joined before this ran.
    return out.replace(HARD_BREAK, "<br>").strip()


def render(md):
    lines = md.split("\n")
    out, bullets, para = [], [], []

    def flush_para():
        if para:
            out.append('    <p class="text-slate-700 leading-relaxed mb-4">%s</p>'
                       % inline(" ".join(para)))
            para.clear()

    def flush_bullets():
        if bullets:
            out.append('    <ul class="list-disc pl-6 space-y-1 mb-4 text-slate-700">')
            out.extend('      <li>%s</li>' % inline(b) for b in bullets)
            out.append('    </ul>')
            bullets.clear()

    for raw in lines:
        line = raw.rstrip() + (HARD_BREAK if raw.endswith("  ") and raw.strip() else "")
        if not line.strip():
            flush_para()
            flush_bullets()
            continue
        heading = re.match(r"^(#{1,3})\s+(.*)$", line)
        if heading:
            flush_para()
            flush_bullets()
            level = len(heading.group(1))
            out.append('    <h%d class="%s">%s</h%d>'
                       % (level, H_CLASSES[level], inline(heading.group(2)), level))
            continue
        if line.strip() == "---":
            flush_para()
            flush_bullets()
            out.append('    <hr class="my-8 border-slate-200">')
            continue
        bullet = re.match(r"^\s*-\s+(.*)$", line)
        if bullet:
            flush_para()
            bullets.append(bullet.group(1))
            continue
        flush_bullets()
        para.append(line.strip())

    flush_para()
    flush_bullets()
    return "\n".join(out)


def main():
    for source, target, title, sibling_href, sibling_label in DOCS:
        with open(source, encoding="utf-8") as fh:
            md = fh.read()
        page = PAGE.format(title=title, source=source, body=render(md),
                           sibling_href=sibling_href, sibling_label=sibling_label)
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(page)
        print(f"{source} -> {target} ({len(page):,} bytes)")


if __name__ == "__main__":
    main()
