-- Action items on the catalog row: the administrative steps a student must complete to
-- apply, generated by agents/generate_action_items.py and served to every student who tracks the
-- program. One-time manual DDL, run by hand in the Supabase SQL editor — PostgREST has no
-- DDL endpoint, so nothing in this repo can run it for you.
--
-- Until this runs, agents/generate_action_items.py aborts naming this file, and the app keeps
-- generating tasks per student in the browser as it does today. That is the pre-fix
-- behaviour, so nothing breaks; it simply stays unfixed.
--
-- WHY THESE LIVE ON THE OPPORTUNITY, NOT ON THE STUDENT'S TRACKER ITEM
-- Tasks are not personalised — the prompt forbids anything about the student's own project,
-- so every student tracking a program was paying for an identical answer and getting a
-- slightly different one. Moving them here makes an add instant, makes the list consistent,
-- and — the actual reason — makes it reviewable. A per-student list is seen by nobody but
-- that student, which is why a fabricated "Algebra 2 prerequisite" survived until a user
-- reported it.

alter table opportunities add column if not exists action_items jsonb;
alter table opportunities add column if not exists action_items_source text;
alter table opportunities add column if not exists action_items_checked_at timestamptz;

-- Shape of each element of action_items:
--   { "text": "Request two recommendation letters",
--     "url": "https://... or null",
--     "basis": "page" | "generic",
--     "evidence": "verbatim quote from the program page, or null" }
--
-- `basis` is the whole point of the column. 'page' means page_text.claim_is_supported()
-- AND page_text.quote_is_on_page() both passed against text we fetched ourselves; the app
-- renders those plainly and everything else under "Typical steps — confirm on the site".
-- `evidence` is kept so the claim stays auditable after the fact and so a re-check can
-- re-verify without paying a model.
--
-- action_items_source records HOW the list was arrived at, so no reader has to re-derive it
-- (same job as the deadline check's `source`):
--   'page-verified'    page read, model ran, at least one task survived verification
--   'page-empty'       page read, but nothing program-specific survived
--   'generic-fallback' page could not be fetched — no model call was made at all
--   'unparsed'         page read, model output unreadable
--
-- action_items_checked_at is stamped ONLY for the first two. A page we could not fetch is a
-- fact about our HTTP client, not about the program, so those rows stay due and a later run
-- retries them — which is free. Stamping a transient 403 would hide the row for 90 days.

create index if not exists opportunities_action_items_checked_at_idx
  on opportunities (action_items_checked_at);

-- ALTER-then-CREATE, deliberately, and the same trap db/mailing_list_schema.sql documents:
-- `create table if not exists` is a no-op against a table that already exists in an older
-- shape, and PostgREST 400s an ENTIRE write on one unknown key. A single missing column
-- here means every action-item write fails and the console reads as "the agent found
-- nothing" rather than "every write was rejected". If you add a column above, it must be an
-- `add column if not exists` line, never only a CREATE.
